"""add creado_en to cliente

Revision ID: 7854b078d1b4
Revises: merge_heads_20260117
Create Date: 2026-01-17 22:16:38.972058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7854b078d1b4'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_20260117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Solo agregar la columna 'creado_en' a la tabla 'clientes'
    op.add_column('clientes', sa.Column('creado_en', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prestamo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('motivo_no_pago', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], name=op.f('pago_prestamo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pago_pkey'))
    )
    op.create_table('gastos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gastos_pkey'))
    )
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('negocio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cliente_pkey')),
    sa.UniqueConstraint('cedula', name=op.f('cliente_cedula_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('prestamos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('interes', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cuotas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('valor_cuota', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('forma_pago', sa.VARCHAR(length=30), server_default=sa.text("'Diario'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('prestamo_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prestamo_pkey'))
    )
    op.create_table('recordatorios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('leido', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('recordatorios_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recordatorios_pkey'))
    )
    op.create_index(op.f('ix_recordatorios_id'), 'recordatorios', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('username', name=op.f('usuario_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
